name: execute_spark_apps.yml
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run spark app of jj.
        run: |
          nohup bash -c 'sh /home/ubuntu/ss-spark/project/scripts/start_to_spark_app.sh jj' > /dev/null 2>&1 
      - name: Run spark app of mk.
        run: |
          nohup bash -c 'sh /home/ubuntu/ss-spark/project/scripts/start_to_spark_app.sh mk' > /dev/null 2>&1
      - name: Run spark app of sw.
        run: |
          nohup bash -c 'sh /home/ubuntu/ss-spark/project/scripts/start_to_spark_app.sh sw' > /dev/null 2>&1
      - name: Move Result.
        run: |
          python3 /home/ubuntu/ss-spark/project/scripts/copy_result_file_executor.py
