name: execute_spark_apps.yml
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run spark app of jj.
        run: |
          sh /home/ubuntu/ss-spark/project/scripts/start_to_spark_app.sh jj
