name: health_check
on:
  schedule:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: health_check
        run: |
          python3 /home/ubuntu/src/hello.py
      - name: Check Result
        run: |
          cat /home/ubuntu/src/output.txt
