name: health_check
on:
  schedule:
    - cron: "10 * * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: health_check
        run: |
          python /home/ubuntu/src/hello.py
      - name: Check Result
        run: |
          cat /home/ubuntu/src/output.txt
