name: run_scraper
on:
  schedule:
    - cron: "34 19 * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Get dc_board ids.
        run: |
          python3 /home/ubuntu/ss-spark/project/scripts/dc_board_id_scraper.py
      - name: Get titles of dc_boards.
        run: |
          python3 /home/ubuntu/ss-spark/project/scripts/dc_scraper.py
